// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVTPYd5gNRedw-LiU8pw-Fg1oil6qpZ78',
    appId: '1:914631924174:web:80a304137a5dacb965f39f',
    messagingSenderId: '914631924174',
    projectId: 'frad-d3156',
    authDomain: 'frad-d3156.firebaseapp.com',
    storageBucket: 'frad-d3156.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRykaZpDPPfrqasBYoZ1sq08BF7xeCAU',
    appId: '1:914631924174:android:cd89ea520d7a3ebd65f39f',
    messagingSenderId: '914631924174',
    projectId: 'frad-d3156',
    storageBucket: 'frad-d3156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBntTFPogo9wRjWzV5tJ1OP7sAnnr3wJWk',
    appId: '1:914631924174:ios:b130bbf8d356366265f39f',
    messagingSenderId: '914631924174',
    projectId: 'frad-d3156',
    storageBucket: 'frad-d3156.firebasestorage.app',
    iosBundleId: 'com.example.frad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBntTFPogo9wRjWzV5tJ1OP7sAnnr3wJWk',
    appId: '1:914631924174:ios:b130bbf8d356366265f39f',
    messagingSenderId: '914631924174',
    projectId: 'frad-d3156',
    storageBucket: 'frad-d3156.firebasestorage.app',
    iosBundleId: 'com.example.frad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVTPYd5gNRedw-LiU8pw-Fg1oil6qpZ78',
    appId: '1:914631924174:web:49e3c356ddaebe9665f39f',
    messagingSenderId: '914631924174',
    projectId: 'frad-d3156',
    authDomain: 'frad-d3156.firebaseapp.com',
    storageBucket: 'frad-d3156.firebasestorage.app',
  );
}
